kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: jnlp
    workingDir: /home/jenkins
  - name: kaniko
    workingDir: /home/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true
    volumneMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  volumes:
  - name: docker-config
    projected:
      sources:
        - secret:
          name: mikej091-docker
          items:
            - key: .dockerconfigjson
              path: config.json
  restartPolicy: Never
