kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: jnlp
    workingDir: /home/jenkins
  - name: kaniko
    workingDir: /home/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    env:
      - name: dockerauth
        value from:
          secretKeyRef:
            name: mikej091-docker
            key: auth
    command:
      - /busybox/cat
    tty: true
  restartPolicy: Never
