kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: jnlp
    workingDir: /home/jenkins
  - name: kaniko
    workingDir: /home/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
        readOnly: true
  volumes:
  - name: docker-config
    secret:
      secretName: mikej091-docker
  restartPolicy: Never
