apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  nodeSelector:
    beta.kubernetes.io/arch: arm
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  volumes:
  - name: docker-config
    secret:  
      secretName: mikej091-docker
  restartPolicy: Never
